version: '2'

services:
    Envroment:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs/:/var/log/nginx
            - ./hosts/hosts:/etc/hosts
        networks:
            - code-network
    php:
        image: zolweb/php7:1.0
        volumes:
            - ./code:/code
            - ./php/mods-available:/usr/local/etc/php/conf.d
            - ./php/php.ini:/conf/php.ini
        networks:
            - code-network
    mysql:
        image: mysql
        environment:
              MYSQL_USER: dbuser
              MYSQL_PASSWORD: dbpassword
              MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql
        environment:
             PMA_HOST: mysql
             PMA_PORT: 3306
             MYSQL_USER: dbuser
             MYSQL_PASSWORD: dbpassword
             MYSQL_ROOT_PASSWORD: root
        ports:
          - '8096:80'
    mariadb:
       image: mariadb
       environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: redis
        container_name: redis
        build: redis/
        ports:
          - '6379:6379'
networks:
    code-network:
        driver: bridge
