version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7-fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
    mysql:
        image: mysql
        environment:
              MYSQL_USER: dbuser
              MYSQL_PASSWORD: dbpassword
              MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql
        environment:
             PMA_HOST: mysql
             PMA_PORT: 3306
             MYSQL_USER: dbuser
             MYSQL_PASSWORD: dbpassword
             MYSQL_ROOT_PASSWORD: root
        ports:
          - '8096:80'
    mariadb:
       image: mariadb
       environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
networks:
    code-network:
        driver: bridge
